name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - version: stable # STABLE
            clippy: true
          - version: 1.63.0 # MSRV
        features:
          - default
          - blocking
          - blocking-https
          - blocking-https-rustls
          - blocking-https-native
          - blocking-https-bundled
          - async
          - async-https
          - async-https-native
          - async-https-rustls
          - async-https-rustls-manual-roots
          - async-arti-hyper
          - async-arti-hyper-native
          - async-arti-hyper-rustls
    steps:
    - uses: actions/checkout@v3
    - name: Generate cache key
      run: echo "${{ matrix.rust.version }} ${{ matrix.features }}" | tee .cache_key
    - name: cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('.cache_key') }}-${{ hashFiles('**/Cargo.toml','**/Cargo.lock') }}
    - name: Set default toolchain
      run: rustup default ${{ matrix.rust.version }}
    - name: Set profile
      run: rustup set profile minimal
    - name: Add clippy
      if: ${{ matrix.rust.clippy }}
      run: rustup component add clippy
    - name: Update toolchain
      run: rustup update
    - name: pin dependencies
      if: matrix.rust.version == '1.63.0'
      run: |
        cargo update -p zstd-sys --precise "2.0.8+zstd.1.5.5"
        cargo update -p time --precise "0.3.20"
        cargo update -p home --precise 0.5.5
        cargo update -p tor-dirclient --precise 0.6.3
        cargo update -p tor-config --precise 0.8.0
        cargo update -p tor-netdoc --precise 0.6.3
        cargo update -p tor-dirmgr --precise 0.9.3
        cargo update -p regex --precise 1.9.6
        cargo update -p zstd-sys --precise 2.0.8+zstd.1.5.5
        cargo update -p time:0.3.31 --precise 0.3.20
        cargo update -p tor-error --precise 0.4.1
        cargo update -p toml:0.7.8 --precise 0.7.3
        cargo update -p toml_edit --precise 0.19.8
        cargo update -p winnow --precise 0.4.1
        cargo update -p serde_spanned --precise 0.6.1
        cargo update -p backtrace --precise 0.3.68
        cargo update -p toml_datetime --precise 0.6.1
        cargo update -p tinystr --precise 0.7.1
    - name: Build
      run: cargo build --features ${{ matrix.features }} --no-default-features
    - name: Clippy
      if: ${{ matrix.rust.clippy }}
      run: cargo clippy --all-targets --features ${{ matrix.features }} --no-default-features -- -D warnings
    - name: Test
      run: cargo test --features ${{ matrix.features }} --no-default-features -- --test-threads=1 --include-ignored
